spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12356
    url: jdbc:mysql://172.16.27.29:30000/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: admin
    password: admin
    host: 172.16.24.9
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 172.16.25.149
    database: 0
    port: 30001
    password: 
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
